## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_in]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
 
## Switches
set_property PACKAGE_PIN V17 [get_ports {sel[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property PACKAGE_PIN V16 [get_ports {sel[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property PACKAGE_PIN W16 [get_ports {Din[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[0]}]
set_property PACKAGE_PIN W17 [get_ports {Din[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[1]}]
set_property PACKAGE_PIN W15 [get_ports {Din[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[2]}]
set_property PACKAGE_PIN V15 [get_ports {Din[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[3]}]
set_property PACKAGE_PIN W14 [get_ports {Din[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[4]}]
set_property PACKAGE_PIN W13 [get_ports {Din[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[5]}]
set_property PACKAGE_PIN V2 [get_ports {Din[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[6]}]
set_property PACKAGE_PIN T3 [get_ports {Din[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din[7]}]
 
## LEDs
set_property PACKAGE_PIN U16 [get_ports {Dout[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[0]}]
set_property PACKAGE_PIN E19 [get_ports {Dout[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[1]}]
set_property PACKAGE_PIN U19 [get_ports {Dout[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[2]}]
set_property PACKAGE_PIN V19 [get_ports {Dout[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[3]}]
set_property PACKAGE_PIN W18 [get_ports {Dout[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[4]}]
set_property PACKAGE_PIN U15 [get_ports {Dout[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[5]}]
set_property PACKAGE_PIN U14 [get_ports {Dout[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[6]}]
set_property PACKAGE_PIN V14 [get_ports {Dout[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Dout[7]}]
	
##Buttons
set_property PACKAGE_PIN U18 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]